server:
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/users?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true